### ISSUE TITLE
Request: Manage user roles

### ISSUE THREAD

**Issue by joshbeard** [antoineco/aco-tomcat#29]
https://github.com/antoineco/aco-tomcat/blob/master/manifests/userdb_entry.pp currently only manages Tomcat users and setting their roles, but not the roles themselves.  For example, I'd like to manage an entry like:

``` xml
<role rolename="somerole"></role>
```

Puppet Labs' Tomcat module, for example, handles this via: https://github.com/puppetlabs/puppetlabs-tomcat/blob/master/manifests/config/server/tomcat_users.pp

Can we get this functionality in this module?  I'd be happy work something up, but not sure how you'd prefer to do this (modify the userdb_entry class or create a new class?)

Thanks!

**Comment by antoineco** [comment]
Hey Josh, that's a good suggestion! I can't tell you when I'll find the time to work on it but I think the Puppet Labs approach is pretty good. The `userdb_entry` type could be revisited to also include the role creation. I'm open to any suggestion :+1:

**Comment by tbe1** [comment]
Hi 

here a proposal - I changed the userdb_entry type accordingly. I introduced a new parameter called add_roles. If this parameter is set to true you can add new roles instead of users to tomcat-users.xml. 
I am new to puppet, so I am not sure if the syntax is 100% perfect.

```
tomcat::userdb_entry { 'newRoles':
  database => 'main UserDatabase',
  add_roles => 'true'
  roles    => ['newRole1', 'newRole2']
}
```

tomcat-users.xml:

```
<tomcat-users>
  <role rolename="newRole1"/>
  <role rolename="newRole2"/>
  <user username="user" password="password" roles="newRole1,newRole2"/>
</tomcat-users>
```

[UserDatabase_role_entry.erb.txt](https://github.com/antoineco/aco-tomcat/files/358793/UserDatabase_role_entry.erb.txt)
[userdb_entry.pp.txt](https://github.com/antoineco/aco-tomcat/files/358794/userdb_entry.pp.txt)

**Comment by antoineco** [comment]
Thanks for the proposal @tbe1 👍 Would you mind submitting a pull request in order to make it easier to review and merge?

**Comment by tbe1** [comment]
Pull request is submitted. 
thomas

**Comment by antoineco** [comment]
Discussion continues in #49
