### ISSUE TITLE
Cannot use templates for log4j configuration

### ISSUE THREAD

**Issue by xaniasd** [antoineco/aco-tomcat#44]
Hi,

in my use-case, I'd like to use ERB templates to configure the log4j settings for tomcat. The current implementation does not allow this, however, as only the source attribute is used when declaring the file resource. A solution would be to expose the content attribute as well (not together with source, as they are mutually exclusive).

**Comment by antoineco** [comment]
Hi @xaniasd, 

This configuration was here mostly for demo purpose since I'd expect each app to deploy its own Log4j settings. I agree that it would be useful to define some settings though.

Log4j is very comprehensive and supporting every possible option will probably be an overkill, so maybe you can suggest what parameters you'd like to set using the module before I start working on it?

**Comment by xaniasd** [comment]
Hi @antoineco 

I understand the reasoning, unfortunately I have to configure some global settings for now. If you want to support all kinds of needs you'll need to make a template as generic as possible. I was thinking more of passing my own template instead. I've created a PR (https://github.com/antoineco/aco-tomcat/pull/45) to show what I mean. I've allowed both content and source as possibilities (for backwards compatibility) however it would be cleaner if we skip source altogether and only support templates. Let me know if that's acceptable, I'll adjust my code to reflect this.

Thanks!

**Comment by antoineco** [comment]
I agree entirely with skipping the "source" parameter altogether, it's not a good pattern for generic modules.

I'd rather let the user generate the file using something cleaner than passing a whole file content as a parameter though, possibly with hash parameters like the way "server.xml" is generated.

Since I'm no Log4j expert, would you have some suggestions regarding the parameters that should absolute be supported?

**Comment by antoineco** [comment]
@xaniasd any progress on that?
