### ISSUE TITLE
Feature: Tomcat Instance Versions

### ISSUE THREAD

**Issue by hanej** [antoineco/aco-tomcat#6]
I've gone through all of the Puppet modules related to Tomcat and this is the best by far.  The only thing I need is the ability to have multiple Tomcat versions on the same host.  The PuppetLabs support module does this by effectively treating each instance as a standalone version which I'm fine with.  Is this something that can be accomplished with this module?

**Comment by antoineco** [comment]
Thanks, I'm glad you like it :) 

It's definitely possible to do it, as long as you install tomcat from the archives and not from your distribution's packaging system. Shouldn't be too much work, I'll look into it.

**Comment by antoineco** [comment]
Jason, I just commited in a new branch called [multi_version](https://github.com/tOnI0/aco-tomcat/tree/multi_version). The defined type `tomcat::instance` now has 2 new parameters: `version` and `archive_source`, just like the main instance.

I've tested my code only on Fedora 21 so far, could you give it a try on your own platform?

**Comment by antoineco** [comment]
Merged to master branch, see commit fd717f12954e59f354085a594480d8fce7cc9063.
I release a new version on the forge with these changes, as well as the ones in issue #7.

**Comment by sabooo** [comment]
@antoineco I am trying to use this module for multiple instances on one machine and each in different directory as requested by @hanej . For a single tomcat, this module works like a gem. My problem is with multiple instances. For multiple instances, do we need to hardcode the instance name, version and archive_source for each instance and other details? Not sure if i am doing it the correct way. I have been able to get puppetlabs-tomcat working by hardcoding all of these values for different instances. I was expecting multiple instance names and other parameters to appear in a drop down menu on Puppet Enterprise PE (through parametrized parameters) to configure as many instances as needed and each with different parameter. Have i lost the track here? is it possible?

**Comment by antoineco** [comment]
Hi @sabooo, I am not too sure how Puppet Enterprise works, but yes you have to configure each instance separately, they won't inherit from the params in the "main" instance if that's the question. However `archive_source` is not mandatory, it will be defined automatically according to `version`.

Regarding hardcoding the values, I assume you want to use Hiera, If that's the case you're right, it doesn't work out of the box with instances since they are defined types, but it's possible to integrate this behavior by using something like this in one of your top-level manifest (i.e. site.pp):

``` puppet
# collect all instances in a Hash variables
$my_tomcat_instances={}
# create resources from this variable
create_resources(tomcat::instance, $my_tomcat_instances)
```

Then you can simply use Hiera (and the Puppet Enterprise front-end I assume) to configure all your instances likes this:

``` yaml
my_tomcat_instances:

  instance1:
    control_port: 8006
    http_port: 8081
    ajp_connector: false

  instance2:
    version: 8.0.5
    ajp_port: 9081
    ajp_params:
      address: 127.0.0.1
      packetSize: 12288
```

If that works for you I can integrate the `create_resources` function into the module.
