### ISSUE TITLE
Package challenge

### ISSUE THREAD

**Issue by HarryHarcourt** [antoineco/aco-tomcat#69]
Hi aco
I am having challenges with your module and I am not sure if it is me or the module.
I have installed the module
I have "include tomcat" in my site.pp against my node
I have tomcat::install_from: package set
I have created a hiera hierarchy which when I use "puppet lookup" against the node for "tomcat::tomcat_navie_package_name" I get the response "tomcat-webapps.noarch" (which is the rpm in the YUM repo I am looking for.
But when I run the puppet agent -t it seems to be defaulting for a different package "tomcat-7.0.54-8.el7_2" which naturally is not in the default yum repo for CentOS.
Any ideas in relation to what I am doing wrong?
Best, and thanks
Ben

**Comment by antoineco** [comment]
Hi @HarryHarcourt, it's actually the module :) CentOS has a new tomcat version since last week and the version expected by the module does not match the one in the repo anymore.

To fix it you have 2 choices:

 - call the module with `version => '7.0.69'`
 - pull the latest commit from master (45f24c18) which fixes your issue

I will draft a new version this or next week so that you don't have to set this parameter explicitly. Sorry for that!

**Comment by HarryHarcourt** [comment]
Thanks - please close this
