### ISSUE TITLE
Will not deploy tomcat correcty in latest ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by joe-hidden** [antoineco/aco-tomcat#94]
When trying to install the tomcat8 using most recent 1.8.4 release on an UBUNTU 16.04.3 LTS it fails to deploy tomcat8-admin and dependencys.

fix: line 192 in params.pp should read  $version = '8.0.32-1ubuntu1.5' to make it work

**Comment by antoineco** [comment]
Indeed, this is a bit shaky. The module used to be kept up to date with the latest OS package versions, however it has gone unmaintained for a while now. I originally wanted to implement a way to read the latest version from the OS package manager, but it never happened due to me not using Puppet anymore.

With that being said, the `package_ensure` parameter lets you set the package version you need.

```puppet
class { 'tomcat':
  package_ensure => '8.0.32-1ubuntu1.5'
}
```
